server:
    port: 8081

debug: 
  true

spring:
    datasource:
       url: jdbc:h2:mem:test
       username: sa
       password:
       driver-class-name: org.h2.Driver
    batch:
      initializer:        enabled: false
    
logging:  config: classpath:log4j2.xml
  file: logs/test-batch.log
  level:
    org.springframework: error    my : debug
    jdbc: error
    jdbc.sqltiming: info 

      
samplejob:
    frequency: 20000
    
Couchdb:
  Host: 10.0.4.73
  Port: 5984
  UserName: ncms
  Password: ncms1216@
    