server:
    port: 8081

debug: enabled

spring:
    datasource:
       url: jdbc:h2:mem:test
       username: sa
       password:
       driver-class-name: org.h2.Driver
       
samplejob:
    frequency: 2000